version: "3.8"
services:
  proxy:
    build: ./Proxy
    environment:
      DB_URI: localhost
      DB_USER: postgres
      DB_PASSWORD: example
    volumes:
      - ./Proxy/.kube/:/.kube
      - ./Proxy/cmd/proxy/config.yaml:/config.yaml
    network_mode: host

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./DB/kubernetes-schema.sql:/docker-entrypoint-initdb.d/kubernetes-schema.sql

  # starts the app in development mode
  explorer:
    build:
      context: ./Explorer
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: example
