version: "3.8"
services:
  dbTestData:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./DB/:/docker-entrypoint-initdb.d/
#Uncomment the following services if needed
#  proxy:
#    build: ./Proxy
#    environment:
#      DB_URI: localhost
#      DB_USER: postgres
#      DB_PASSWORD: example
#    volumes:
#      - ./Proxy/.kube/:/.kube
#    network_mode: host

# starts the app in development mode
#  explorer:
#    build:
#      context: ./Explorer
#    ports:
#      - "3000:3000"
#    environment:
#      DB_URI: db/postgres
#      DB_USER: postgres
#      DB_PASSWORD: example
