# This workflow will build all images and run pre-commit

name: CI
on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  pre-commit:
    runs-on: "ubuntu-latest"
    steps:
    - run: pip install pre-commit
    - run: pre-commit run --all
  build-images:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build images
        uses: docker/bake-action@v3
