# This workflow will build all images and run pre-commit

name: CI
on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  pre-commit:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: cd Explorer && npm install && cd .. # We use the eslint defined in the package.json
      - run: pip install pre-commit
      - run: pre-commit run --all
        env: { SKIP: golangci-lint-mod }
  golangci-lint-mod:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.52
          working-directory: Proxy
  build-images:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build images
        uses: docker/bake-action@v3
